######## Recall Service

# Default: 8980, which port to create the server
servicePort: 8084

# Default: null, open a port for prometheus monitoring tool, if set, user can check the
# performance using prometheus
monitorPort: 1238

# default: false, if load saved index, set true
loadSavedIndex: true

# default: false, if true, the built index will be saved to indexPath. Ignored when
# loadSavedIndex=true
saveBuiltIndex: true

# default: null, path to saved index path, must be provided if loadSavedIndex=true or
# saveBuiltIndex=true
indexPath: ./item.idx

# default: false
getFeatureFromFeatureService: true

# default: localhost:8980, feature service target
featureServiceURL: localhost:8085

itemIDColumn: tweet_id
# itemFeatureColumns: item

# default: null, user model path must be provided if getFeatureFromFeatureService=false
# userModelPath:

# default: null, item model path must be provided if loadSavedIndex=false and initialDataPath is
# not orca predict result
# itemModelPath:

# default: null, Only support parquet file
initialDataPath: /home/yina/Documents/data/recsys/full_data/vec_feature_item_prediction_1000.parquet

# default: 1, number of models used in inference service
# modelParallelism: 3