######## Feature Service

### Basic setting

# Default: 8980, which port to create the server
servicePort: 8085

# Default: null, open a port for prometheus monitoring tool, if set, user can check the
# performance using prometheus
monitorPort: 1236

# 'kv' or 'inference' default: kv
serviceType: kv

# default: false, if need to load initial data to redis, set true
loadInitialData: true

# default: "", prefix for redis key
redisKeyPrefix: 2tower_

# default: 0, item slot type on redis cluster. 0 means slot number use the default value 16384, 1 means all keys save to same slot, 2 means use the last character of id as hash tag.
redisClusterItemSlotType: 1

# default: null, if loadInitialData=true, initialUserDataPath or initialItemDataPath must be
# provided. Only support parquet file
initialUserDataPath: /home/yina/Documents/data/recsys/wnd_813/vec_feature_user_prediction_2000.parquet
# initialItemDataPath:

# default: null, if loadInitialData=true and initialUserDataPath != null, userIDColumn and
# userFeatureColumns must be provided
userIDColumn: enaging_user_id
userFeatureColumns: prediction

# default: null, if loadInitialData=true and initialItemDataPath != null, userIDColumn and
# userFeatureColumns must be provided
# itemIDColumn:
# itemFeatureColumns:

# default: null, user model path or item model path must be provided if serviceType
# contains 'inference'. If serviceType=kv, usermodelPath, itemModelPath and modelParallelism will
# be ignored
# userModelPath: /home/yina/Documents/model/recys2021/2tower/exp8/user-model

# default: null, user model path or item model path must be provided if serviceType
# contains 'inference'. If serviceType=kv, usermodelPath, itemModelPath and modelParallelism will
# be ignored
# itemModelPath:

# default: 1, number of models used for inference
# modelParallelism: 3

### Redis Configuration
# default: localhost:6379
redisUrl: 10.239.158.177:12000,10.239.158.177:12001,10.239.158.177:12002

# default: 256, JedisPoolMaxTotal
# redisPoolMaxTotal:
