# Configure the variables to be passed into the templates.

nfsServerIp: your_nfs_server_ip
nfsPath: a_nfs_shared_folder_path_on_the_server
couchdbRootUsername: YWRtaW4= # Reset is optional
couchdbRootPassword: cGFzc3dvcmQ= # Reset is optional
# Set the versions according to your images
pccsImageName: intelanalytics/pccs:0.3.0-SNAPSHOT
dkeyserverImageName: intelccc/ehsm_dkeyserver:0.3.0
couchdbImageName: couchdb:3.2
dkeycacheImageName: intelccc/ehsm_dkeycache:0.3.0
ehsmKmsImageName: intelccc/ehsm_kms:0.3.0
pccsIP: your_pccs_ip_to_use_as
dkeyserverIP: your_dkeyserver_ip_to_use_as
kmsIP: your_kms_ip_to_use_as
# Below are used by pccs
apiKey: your_intel_pcs_server_subscription_key_obtained_through_web_registeration # Refer to README for obtaining pcs api key
# The below three service IPs are different IP addresses that unused in your subnetwork
# Please do not use the same real IPs as nodes
httpsProxyUrl: your_usable_https_proxy_url
countryName: your_country_name
cityName: your_city_name
organizaitonName: your_organizaition_name
commonName: server_fqdn_or_your_name
emailAddress: your_email_address
serverPassword: your_server_password_to_use # Do not use a pure-number password
