######## Feature Service

### Basic setting

# Default: 8980, which port to create the server
servicePort: 8085

# Default: null, open a port for prometheus monitoring tool, if set, user can check the
# performance using prometheus
monitorPort: 1236

# 'kv' or 'inference' default: kv
serviceType: kv

# default: "", prefix for redis key
redisKeyPrefix: 2tower_

# default: 0, item slot type on redis cluster. 0 means slot number use the default value 16384, 1 means all keys save to same slot, 2 means use the last character of id as hash tag.
redisClusterItemSlotType:

# default: null, if serviceType='kv,inference', userFeatureColumns must be provided
# userFeatureColumns: prediction

# default: null, if serviceType='kv,inference', itemFeatureColumns must be provided
# itemFeatureColumns:

# default: null, user model path or item model path must be provided if serviceType
# contains 'inference'. If serviceType=kv, usermodelPath, itemModelPath and modelParallelism will
# be ignored
# userModelPath: /home/yina/Documents/model/recys2021/2tower/exp8/user-model

# default: null, user model path or item model path must be provided if serviceType
# contains 'inference'. If serviceType=kv, usermodelPath, itemModelPath and modelParallelism will
# be ignored
# itemModelPath:

# default: 1, number of models used for inference
# modelParallelism: 3

### Redis Configuration
# default: localhost:6379
# redisUrl: 10.239.158.177:12000,10.239.158.177:12001,10.239.158.177:12002

# default: 256, JedisPoolMaxTotal
# redisPoolMaxTotal:

# default: 2, The redis log emit interval in minutes
logInterval: 2
