apiVersion: v1
kind: Pod
metadata:
  name: spark-deployment
  namespace: default
spec:
  containers:
  - name: spark-example
    imagePullPolicy: Never
    volumeMounts:
#    - name: device-plugin
#      mountPath: /var/lib/kubelet/device-plugins
    - name: sgx-enclave
      mountPath: /dev/sgx/enclave
    - name: sgx-provision
      mountPath: /dev/sgx/provision
    - name: aesm
      mountPath: /var/run/aesmd
    - name: data-exchange
      mountPath: /opt/occlum_spark/data
    securityContext:
      privileged: true
    env:
    - name: NETTY_THREAD
      value: "32"
    - name: SGX_MEM_SIZE
      value: "10GB"
    - name: SGX_THREAD
      value: "512"
    - name: SGX_HEAP
      value: "512MB"
    - name: SGX_KERNEL_HEAP
      value: "1GB"
  volumes:
#    - name: device-plugin
#      hostPath:
#        path: /var/lib/kubelet/device-plugins
  - name: sgx-enclave
    hostPath:
      path: /dev/sgx_enclave
  - name: sgx-provision
    hostPath:
      path: /dev/sgx_provision
  - name: aesm
    hostPath:
      path: /var/run/aesmd
  - name: data-exchange
    hostPath:
      path: /tmp
