site_name: Analytics Zoo
theme: null
extra_css: [extra.css]
theme_dir: mkdocs_windmill 
repo_name: 'Fork on GitHub '
repo_url: 'https://github.com/intel-analytics/analytics-zoo'
extra:
    version: latest
    article_nav_top: false
    article_nav_bottom: false

pages:
- Overview: index.md 
- Releases: 
  - Download: release-download.md 
  - Documentation: release-docs.md
- Programming Guide: 
  - Pipeline APIs:
    - DataFrame and ML Pipeline: programming-guide.md
    - Autograd: programming-guide.md
    - Transfer Learning: programming-guide.md
  - Feature Engineering:
    - Working with Images: programming-guide.md
  - Built-in Models:
    - Object Detection: programming-guide.md
    - Image Classification: programming-guide.md
    - Text Classification: programming-guide.md
    - Recommedation: programming-guide.md
  - Use Cases:
    - overview: programming-guide.md
    - Anomaly Detection: programming-guide.md
- User Guide:
  - Python
    - Install: PythonUserGuide/install.md
    - Run: PythonUserGuide/install.md
    - Examples: PythonUserGuide/python-examples.md
  - Scala 
    - Install: ScalaUserGuide/install.md
    - Run: ScalaUserGuide/install.md
    - Examples: ScalaUserGuide/examples.md
- API Guide:
  - Pipeline APIs
    - NNFrames: APIGuide/PipelineAPI/nnframes.md
    - Autograd: APIGuide/PipelineAPI/nnframes.md
    - Net: APIGuide/PipelineAPI/nnframes.md
  - Feature Engineering
    - Image: APIGuide/PipelineAPI/nnframes.md
  - Models
    - Object Detection: programming-guide.md
    - Image Classification: programming-guide.md
    - Text Classification: programming-guide.md
    - Recommedation: programming-guide.md
- Powered by: powered-by.md
- FAQ and Known Issues: known-issues.md
