site_name: BigDL Project
theme: null
extra_css: [extra.css]
theme_dir: mkdocs_windmill 
repo_name: 'Fork on GitHub '
repo_url: 'https://github.com/intel-analytics/BigDL'
extra:
    version: latest
    article_nav_top: false
    article_nav_bottom: false


pages:
- Overview: index.md 
- Releases: 
  - Download: release-download.md 
  - Documentation: release-docs.md
- Getting Started: getting-started.md
- Scala User Guide: 
  - Install: 
    - Use Pre-built Libs: ScalaUserGuide/install-pre-built.md
    - Build from Source Code: ScalaUserGuide/install-build-src.md 
  - Run: ScalaUserGuide/run.md
  - Configuration: ScalaUserGuide/configuration.md
  - Examples: ScalaUserGuide/examples.md
  - More Resources: ScalaUserGuide/resources.md
- Python User Guide: 
  - Install:
    - From pip: PythonUserGuide/install-from-pip.md
    - Without pip: PythonUserGuide/install-without-pip.md
  - Run:
    - After pip install: PythonUserGuide/run-from-pip.md
    - Without pip install: PythonUserGuide/run-without-pip.md
  - Examples: PythonUserGuide/python-examples.md
  - More Examples and Tutorials: PythonUserGuide/python-resources.md
- Programming Guide:
  - Define a Model:
    - Using Sequential API: ProgrammingGuide/Model/Sequential.md
    - Using Functional API: ProgrammingGuide/Model/Functional.md
  - Optimization: ProgrammingGuide/optimization.md
  - Use Spark ML: ProgrammingGuide/MLPipeline.md
  - Visualization: ProgrammingGuide/visualization.md
  - Run on Amazon EC2: ProgrammingGuide/run-on-ec2.md
  - Run on Google Cloud Dataproc: ProgrammingGuide/run-on-dataproc.md
  - Tensorflow Support: ProgrammingGuide/tensorflow-support.md
  - Caffe Support: ProgrammingGuide/caffe-support.md
  - Quantization Support: ProgrammingGuide/quantization-support.md
  - Define new Layer/Criterion: ProgrammingGuide/add-layer-criterion.md
- API Guide:
  - Data: APIGuide/Data.md
  - Model: APIGuide/Module.md
  - Layers: 
    - Containers:  APIGuide/Layers/Containers.md
    - Simple Layers: APIGuide/Layers/Simple-Layers.md
    - Convolution Layers: APIGuide/Layers/Convolution-Layers.md
    - Pooling Layers:  APIGuide/Layers/Pooling-Layers.md
    - Activations: APIGuide/Layers/Activations.md
    - Embedding Layers: APIGuide/Layers/Embedding-Layers.md
    - Merge/Split Layers: APIGuide/Layers/MergeSplit-Layers.md
    - Math Layers: APIGuide/Layers/Math-Layers.md
    - Padding Layers: APIGuide/Layers/Padding-Layers.md
    - Normalization Layers:  APIGuide/Layers/Normalization-Layers.md
    - Dropout Layers: APIGuide/Layers/Dropout-Layers.md
    - Distance Layers: APIGuide/Layers/Distance-Layers.md
    - Recurrent Layers:  APIGuide/Layers/Recurrent-Layers.md
    - Recursive Layers:  APIGuide/Layers/Recursive-Layers.md
    - Utilities: APIGuide/Layers/Utilities.md
  - Losses: APIGuide/Losses.md
  - Initalizers: APIGuide/Initializers.md
  - Regularizers: APIGuide/Regularizers.md
  - Optimizer: APIGuide/Optimizers/Optimizer.md
  - Optim Methods:
    - OptimMethod: APIGuide/Optimizers/OptimMethod.md 
    - Optimization Algorithms: APIGuide/Optimizers/Optim-Methods.md
  - Triggers: APIGuide/Triggers.md
  - Metrics:  APIGuide/Metrics.md
  - Full API docs:
    - Scala Docs: APIGuide/scaladoc.md
    - Python API Docs: APIGuide/python-api-doc.md
- Powered by: powered-by.md
- Known Issues: known-issues.md
- Presentations: presentations.md
