name: BigDL Release Scala

on:  
  workflow_dispatch:
  pull_request:


permissions:
  contents: read

jobs:
  bigdl-release-scala:
    runs-on: [self-hosted, Bree]
    # if: ${{ github.actor == 'Le-Zheng' }}
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.6.3
    - name: Set up Maven Settings
      uses: analytics-zoo/maven-settings-action@dev
      with:
        sonatypeSnapshots: true
        apacheSnapshots: true
        servers: |
          [{
            "id": "central",
            "configuration": {
              "httpConfiguration": {
                "all": {
                  "connectionTimeout": "3600000",
                  "readTimeout": "3600000"
                  }    
                }
              }
          },{
            "id": "ossrh",
            "username": "${{ secrets.OSSRH_USERNAME }}",
            "password": "${{ secrets.OSSRH_PASSWORD }}",
            "configuration": {
              "timeout": "3600000"
            }
          },{
            "id": "releases",
            "username": "${{ secrets.RELEASES_USERNAME }}",
            "password": "${{ secrets.RELEASES_PASSWORD }}"
          },{
            "id": "snapshots",
            "username": "${{ secrets.SNAPSHOTS_USERNAME }}",
            "password": "${{ secrets.SNAPSHOTS_PASSWORD }}"
          }]
        proxies: |
          [{
            "id": "uc-http",
            "active": "true",
            "protocol": "http",
            "host": "${{ secrets.HTTP_PROXY_HOST_2 }}",
            "port": "${{ secrets.HTTP_PROXY_PORT_2 }}",
            "nonProxyHosts": "10.239.45.219|localhost"
          },{
            "id": "uc-https",
            "active": "true",
            "protocol": "https",
            "host": "${{ secrets.HTTP_PROXY_HOST_2 }}",
            "port": "${{ secrets.HTTP_PROXY_PORT_3 }}",
            "nonProxyHosts": "10.239.45.219|localhost"
          }]
        mirrors: |
          [{
            "id": "ardaNexus",
            "mirrorOf": "*",
            "name": "Arda's nexus",
            "url": "${NEXUS_URL}"
          }]
    - name: Maven clean deploy
      run: |
        set -x
        set -e
        ls
        #spark3.4.1
        cp scala/pom.xml scala/pom.xml.origin
        cp scala/common/spark-version/pom.xml scala/common/spark-version/pom.xml.origin
        cp scala/common/spark-version/3.0/pom.xml scala/common/spark-version/3.0/pom.xml.origin
        cp scala/dllib/pom.xml scala/dllib/pom.xml.origin
        cp scala/orca/pom.xml scala/orca/pom.xml.origin
        cp scala/friesian/pom.xml scala/friesian/pom.xml.origin
        cp scala/grpc/pom.xml scala/grpc/pom.xml.origin
        cp scala/serving/pom.xml scala/serving/pom.xml.origin
        cp scala/ppml/pom.xml scala/ppml/pom.xml.origin
        cp scala/assembly/pom.xml scala/assembly/pom.xml.origin
        sed -i 's/<artifactId>${spark-version.project}<\/artifactId>/<artifactId>${spark-version.project}-${SPARK_PLATFORM}<\/artifactId>/' scala/dllib/pom.xml
        sed -i 's/<artifactId>3.0<\/artifactId>/<artifactId>3.0-${SPARK_PLATFORM}<\/artifactId>/' scala/common/spark-version/3.0/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_3.4.1<\/artifactId>/' scala/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_3.4.1<\/artifactId>/' scala/common/spark-version/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_3.4.1<\/artifactId>/' scala/common/spark-version/3.0/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_3.4.1<\/artifactId>/' scala/dllib/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_3.4.1<\/artifactId>/' scala/orca/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_3.4.1<\/artifactId>/' scala/friesian/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_3.4.1<\/artifactId>/' scala/grpc/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_3.4.1<\/artifactId>/' scala/serving/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_3.4.1<\/artifactId>/' scala/ppml/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_3.4.1<\/artifactId>/' scala/assembly/pom.xml
        mvn clean deploy -DskipTests -Dspark.version=3.4.1 -DSPARK_PLATFORM=SPARK_3.1 -P spark_3.x -P sign -P release-assembly -X -DstagingProgressTimeoutMinutes=20 -Dgpg.passphrase=BigDL2017 --file scala/pom.xml 
        mv scala/pom.xml.origin scala/pom.xml
        mv scala/common/spark-version/pom.xml.origin scala/common/spark-version/pom.xml
        mv scala/common/spark-version/3.0/pom.xml.origin scala/common/spark-version/3.0/pom.xml
        mv scala/dllib/pom.xml.origin scala/dllib/pom.xml
        mv scala/orca/pom.xml.origin scala/orca/pom.xml
        mv scala/friesian/pom.xml.origin scala/friesian/pom.xml
        mv scala/grpc/pom.xml.origin scala/grpc/pom.xml
        mv scala/serving/pom.xml.origin scala/serving/pom.xml
        mv scala/ppml/pom.xml.origin scala/ppml/pom.xml
        mv scala/assembly/pom.xml.origin scala/assembly/pom.xml

        #spark2.4.6
        cp scala/pom.xml scala/pom.xml.origin
        cp scala/common/spark-version/pom.xml scala/common/spark-version/pom.xml.origin
        cp scala/common/spark-version/2.0/pom.xml scala/common/spark-version/2.0/pom.xml.origin
        cp scala/dllib/pom.xml scala/dllib/pom.xml.origin
        cp scala/orca/pom.xml scala/orca/pom.xml.origin
        cp scala/friesian/pom.xml scala/friesian/pom.xml.origin
        cp scala/grpc/pom.xml scala/grpc/pom.xml.origin
        cp scala/serving/pom.xml scala/serving/pom.xml.origin
        cp scala/ppml/pom.xml scala/ppml/pom.xml.origin
        cp scala/assembly/pom.xml scala/assembly/pom.xml.origin
        sed -i 's/<artifactId>${spark-version.project}<\/artifactId>/<artifactId>${spark-version.project}-${SPARK_PLATFORM}<\/artifactId>/' scala/dllib/pom.xml
        sed -i 's/<artifactId>2.0<\/artifactId>/<artifactId>2.0-${SPARK_PLATFORM}<\/artifactId>/' scala/common/spark-version/2.0/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_2.4.6<\/artifactId>/' scala/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_2.4.6<\/artifactId>/' scala/common/spark-version/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_2.4.6<\/artifactId>/' scala/common/spark-version/2.0/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_2.4.6<\/artifactId>/' scala/dllib/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_2.4.6<\/artifactId>/' scala/orca/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_2.4.6<\/artifactId>/' scala/friesian/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_2.4.6<\/artifactId>/' scala/grpc/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_2.4.6<\/artifactId>/' scala/serving/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_2.4.6<\/artifactId>/' scala/ppml/pom.xml
        sed -i 's/<artifactId>bigdl-parent-spark_${spark.version}<\/artifactId>/<artifactId>bigdl-parent-spark_2.4.6<\/artifactId>/' scala/assembly/pom.xml
        mvn clean deploy -DskipTests -Dspark.version=2.4.6 -DSPARK_PLATFORM=SPARK_2.4 -P spark_2.x -P sign -P release-assembly -X -DstagingProgressTimeoutMinutes=20 -Dgpg.passphrase=BigDL2017 --file scala/pom.xml
        mv scala/pom.xml.origin scala/pom.xml
        mv scala/common/spark-version/pom.xml.origin scala/common/spark-version/pom.xml
        mv scala/common/spark-version/2.0/pom.xml.origin scala/common/spark-version/2.0/pom.xml
        mv scala/dllib/pom.xml.origin scala/dllib/pom.xml
        mv scala/orca/pom.xml.origin scala/orca/pom.xml
        mv scala/friesian/pom.xml.origin scala/friesian/pom.xml
        mv scala/grpc/pom.xml.origin scala/grpc/pom.xml
        mv scala/serving/pom.xml.origin scala/serving/pom.xml
        mv scala/ppml/pom.xml.origin scala/ppml/pom.xml
        mv scala/assembly/pom.xml.origin scala/assembly/pom.xml
