name: BigDL Build Portable Zip

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'python/llm/portable-zip/**'
  workflow_dispatch:


jobs:
  build-cpython:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.2
      - uses: actions/checkout@v4
        with:
          repository: 'python/cpython'
          ref: '3.9'
      - name: Build cpython
        run: |
          ./Tools/msi/buildrelease.bat -x64 --skip-doc --skip-nuget --skip-msi
      - name: Rename artifact
        shell: bash
        run: |
          cd ./PCbuild/amd64/en-us
          ls | xargs -I {} mv {} cpython-embed-zip.zip
          cd ../../..
      - uses: actions/upload-artifact@v4
        with:
          name: cpython-3.9-embed-zip
          path: ./PCbuild/amd64/en-us/cpython-embed-zip.zip
  build-portable-zip:
    needs: build-cpython
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: cpython-3.9-embed-zip
          path: ./python/llm/portable-zip/
      - name: Build Portable Zip
        shell: cmd
        run: |
          cd .\python\llm\portable-zip
          setup.bat --python-zip
          cd ..\..\..
      - uses: actions/upload-artifact@v4
        with:
          name: bigdl-llm-portable
          path: ./python/llm/portable-zip/bigdl-llm-portable.zip
  generate-gpg-sign:
    needs: build-portable-zip
    runs-on: [self-hosted, Bree]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: bigdl-llm-portable
      - name: Generate GPG Sign
        shell: bash
        run: |
          gpg --armor --detach-sign bigdl-llm-portable.zip
      - uses: actions/upload-artifact@v4
        with:
          name: bigdl-llm-portable-gpg-sign
          path: ./bigdl-llm-portable.zip.asc
