name: Chronos Example Python Spark py37

# Cancel previous runs in the PR when you push new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

# Controls when the action will run. 
on:
  # Trigger the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    paths:
      - 'python/chronos/src/**'
      - 'python/chronos/example/**'
      - 'python/nano/src/**'
      - 'python/orca/src/bigdl/orca/automl/**'
      - 'python/orca/src/bigdl/orca/data/**'
      - '.github/workflows/chronos-example-python-spark.yml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Chronos-example:
    runs-on: [ self-hosted, Gondolin, ubuntu-20.04-lts ]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: ./.github/actions/jdk-setup-action
      - name: Set up Maven
        uses: ./.github/actions/maven-setup-action

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Chronos example
        shell: bash
        run: |
          conda remove -n chronos-prvn-env -y --all
          conda create -n chronos-prvn-env -y python==3.7.10 setuptools==58.0.4 -c ${GONDOLIN_CONDA_CHANNEL} --override-channels
          source activate chronos-prvn-env
          apt-get update
          apt-get install -y libgl1
          apt-get install patchelf
          pip uninstall -y bigdl-friesian bigdl-friesian-spark3 bigdl-dllib bigdl-dllib-spark3 bigdl-orca pyspark bigdl-orca-spark3 bigdl-chronos bigdl-chronos-spark3 bigdl-nano bigdl-friesian bigdl-friesian-spark3
          wget https://raw.githubusercontent.com/analytics-zoo/gha-cicd-env/main/python-requirements/requirements-chronos-python-ut.txt -O ${{ github.workspace }}/requirements-chronos-python-ut.txt
          pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} -r ${{ github.workspace }}/requirements-chronos-python-ut.txt
          bash python/dev/release_default_linux_spark246.sh default false false
          bash python/nano/dev/build_and_install.sh linux default false pytorch --force-reinstall --no-deps -U
          whl_name=`ls python/nano/dist/`
          pip install -i https://pypi.python.org/simple python/nano/dist/${whl_name}[tensorflow,pytorch,inference]
          pip install -i https://pypi.python.org/simple python/dllib/src/dist/bigdl_dllib-*-py3-none-manylinux1_x86_64.whl
          pip install -i https://pypi.python.org/simple python/orca/src/dist/bigdl_orca-*-py3-none-manylinux1_x86_64.whl
          pip install -i https://pypi.python.org/simple python/chronos/src/dist/bigdl_chronos-*-py3-none-manylinux1_x86_64.whl
          pip install -i https://pypi.python.org/simple jupyter
          export SPARK_LOCAL_HOSTNAME=localhost
          export KERAS_BACKEND=tensorflow
          HOROVOD_WITH_PYTORCH=1; HOROVOD_WITH_GLOO=1; pip install --no-cache-dir horovod==0.24.2
          bash python/chronos/dev/example/run-example-tests.sh
          source deactivate
          conda remove -n chronos-prvn-env -y --all
        env:
          BIGDL_ROOT: ${{ github.workspace }}
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}

