name: Friesian Docker Build

on: 
# push:
#   paths:
#      - 'scala/friesian/**'
#      - '.github/workflows/friesian-docker-build.yml'
#      - '.github/actions/friesian-docker-build-action/action.yml'
# pull_request:
#   branches: [ main ]
#   paths:
#      - 'scala/friesian/**'
#      - '.github/workflows/friesian-docker-build.yml'
#      - '.github/actions/friesian-docker-build-action/action.yml'
  #  schedule:
  #    - cron: '0 12 * * *' # GMT time, 12:00 GMT == 20:00 China
  workflow_dispatch:
    inputs:
      artifact:
        description: 'select which job to run("all" will make all jobs run)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - serving-jar-package
          - docker-build
      tag:
        description: 'docker image tag (e.g. 2.1.0-SNAPSHOT)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  serving-jar-package:
    if: ${{ github.event.inputs.artifact == 'serving-jar-package' || github.event.inputs.artifact == 'all' }}
    runs-on:  [self-hosted,alpha,Bree,ubuntu-20.04-lts]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # actions/checkout@v3

      - name: Set up JDK8
        uses: ./.github/actions/jdk-setup-action

      - name: Set up maven
        uses: ./.github/actions/maven-setup-action

      - name: Build with Maven
        run: |
          cd scala
          mvn clean package -P serving,spark_3.x -pl "-assembly,-serving,-ppml" -DskipTests
          ls -alh ./friesian/target/

          # upload
          sshpass -p "${SOURCEFORGE_PW}" \
          scp ./friesian/target/bigdl-friesian-*-serving.jar \
          intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/friesian-serving-jars


  friesian-docker-build:
    needs: serving-jar-package
    if: ${{ github.event.inputs.artifact == 'docker-build' || github.event.inputs.artifact == 'all' }}
    runs-on: [ self-hosted, Shire ]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # actions/checkout@v3
      - name: set env
        run: |
          echo "TAG=${{github.event.inputs.tag||'latest'}}" >> $GITHUB_ENV
      - name: Set up JDK8
        uses: ./.github/actions/jdk-setup-action
      - name: Build docker
        uses: ./.github/actions/friesian-docker-build-action

