name: LLM Unit Tests on Linux

# Cancel previous runs in the PR when you push new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'python/llm/**'
      - '.github/workflows/llm_unit_tests_linux.yml'
      - '.github/actions/llm/setup-llm-env/action.yml'
      - '.github/actions/llm/remove-llm-env/action.yml'
      - '.github/actions/llm/cli-test/action.yml'
      - '.github/actions/llm/inference-test/action.yml'
      - '.github/actions/llm/langchain-test/action.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'python/llm/**'
      - '.github/workflows/llm_unit_tests_linux.yml'
      - '.github/actions/llm/setup-llm-env/action.yml'
      - '.github/actions/llm/remove-llm-env/action.yml'
      - '.github/actions/llm/cli-test/action.yml'
      - '.github/actions/llm/inference-test/action.yml'
      - '.github/actions/llm/langchain-test/action.yml'
  workflow_dispatch:

env:
  INT4_CKPT_DIR: ./llm/ggml-actions/stable
  LLAMA_INT4_CKPT_PATH: ./llm/ggml-actions/stable/bigdl_llm_llama_7b_q4_0.bin
  GPTNEOX_INT4_CKPT_PATH: ./llm/ggml-actions/stable/bigdl_llm_redpajama_7b_q4_0.bin
  BLOOM_INT4_CKPT_PATH: ./llm/ggml-actions/stable/bigdl_llm_bloom_7b_q4_0.bin
  STARCODER_INT4_CKPT_PATH: ./llm/ggml-actions/stable/bigdl_llm_santacoder_1b_q4_0.bin

  LLM_DIR: ./llm
  ORIGINAL_CHATGLM_6B_PATH: ./llm/chatglm2-6b/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  llm-unit-test-linux-avx512:
    runs-on: [ self-hosted, llm, AVX512, ubuntu-20.04-lts ]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    env:
      THREAD_NUM: 6
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools==58.0.4
          python -m pip install --upgrade wheel

      - name: Run LLM install (all) test
        uses: ./.github/actions/llm/setup-llm-env
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}

      - name: Download ckpt models
        run: |
          if [ ! -d $LLAMA_INT4_CKPT_PATH ]; then
            echo "Directory $LLAMA_INT4_CKPT_PATH not found. Downloading from FTP server..."
            wget --no-verbose $LLM_FTP_URL/${LLAMA_INT4_CKPT_PATH:1} -P $INT4_CKPT_DIR
          fi
          if [ ! -d $GPTNEOX_INT4_CKPT_PATH ]; then
            echo "Directory $GPTNEOX_INT4_CKPT_PATH not found. Downloading from FTP server..."
            wget --no-verbose $LLM_FTP_URL/${GPTNEOX_INT4_CKPT_PATH:1} -P $INT4_CKPT_DIR
          fi
          if [ ! -d $BLOOM_INT4_CKPT_PATH ]; then
            echo "Directory $BLOOM_INT4_CKPT_PATH not found. Downloading from FTP server..."
            wget --no-verbose $LLM_FTP_URL/${BLOOM_INT4_CKPT_PATH:1} -P $INT4_CKPT_DIR
          fi
          if [ ! -d $STARCODER_INT4_CKPT_PATH ]; then
            echo "Directory $STARCODER_INT4_CKPT_PATH not found. Downloading from FTP server..."
            wget --no-verbose $LLM_FTP_URL/${STARCODER_INT4_CKPT_PATH:1} -P $INT4_CKPT_DIR
          fi
          if [ ! -d $ORIGINAL_CHATGLM_6B_PATH ]; then
            echo "Directory $ORIGINAL_CHATGLM_6B_PATH not found. Downloading from FTP server..."
            wget -r -nH --no-verbose --cut-dirs=1 $LLM_FTP_URL/${ORIGINAL_CHATGLM_6B_PATH:1} -P $LLM_DIR
          fi

      - name: Run LLM cli test
        uses: ./.github/actions/llm/cli-test
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}

      - name: Run LLM inference test
        uses: ./.github/actions/llm/inference-test
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}

      - name: Run LLM langchain test
        uses: ./.github/actions/llm/langchain-test
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}

      - name: Clean up test environment
        uses: ./.github/actions/llm/remove-llm-env
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
