name: Scanner-snyk-scala
on:
#  pull_request:
#    branchs: [ main ]
  schedule:
    - cron: '0 4 * * 0' # GMT time, 4:00 GMT == 12:00 China Every Sunday
  workflow_dispatch:
    inputs:
      snyk_apitoken:
        description: 'Snyk token'
        required: false
        type: string        
        default: 'monitor'
      snyk_org:
        description: 'Enter synk org: (eg- iags_mlp)'
        required: true
        type: string
        default: 'iags_mlp'

jobs:
  snyk-scala:
    runs-on: [self-hosted, SDL]
    steps:
    - uses: actions/checkout@v3
    - name: set env
      run: |
        sed -i 's/<artifactId>${spark-version.project}<\/artifactId>/<artifactId>2.0-SPARK_2.4<\/artifactId>/' scala/dllib/pom.xml
        sed -i 's/<artifactId>2.0<\/artifactId>/<artifactId>2.0-SPARK_2.4<\/artifactId>/' scala/common/spark-version/2.0/pom.xml
    - name: "run Snyk test scan"
      env: 
          no_proxy: snyk.devtools.intel.com, intel.com
      run: |
        cd scala
        snyk monitor --all-projects
        cd -
