name: stable-diffusion-win

permissions:
  contents: read

on:
  # pull_request:
  #   branchs: [ main ]
  schedule:
    - cron: '0 3 * * *' # GMT time, 3:00 GMT == 3:00 China Everyday
  workflow_dispatch:

jobs:
  stable-diffusion-win:
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]
    steps:
      - name: Download log
        run: |
          wget ftp://10.112.231.51:8821/stable-diffusion/ui-test.log --ftp-user=${{ secrets.FTP_USERNAME }} --ftp-password=${{ secrets.FTP_PASSWORD }}
          cat ui-test.log
          content=$( cat "ui-test.log" )
          rm ui-test.log
          if [[ " $content " =~ "6 passed" ]]
            then
              echo "All tests passed"
              exit 0
            else
              echo "Some tests failed"
              exit 1
          fi
          
